version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: udemy-docker-rails
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - udemy-docker-rails-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - udemy-docker-rails-redis:/var/lib/redis/data

  udemy-docker-rails:
    build:
      context: .
    volumes:
      - ./udemy-docker-rails:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - udemy-docker-rails
    ports:
      - '8020:8020'

volumes:
  udemy-docker-rails-postgres:
  udemy-docker-rails-redis: